### ISSUE TITLE
Error: 'rest' is not a registered wp command. See 'wp help'.

### ISSUE THREAD

**Issue by a42** [danielbachhuber/wp-rest-cli#27]
Hi ther

After installing the package as stated in the readme-file I get the error (though I could not update the wp-cli --nightly as plain user, so I did that as root user...) :

Error: 'rest' is not a registered wp command. See 'wp help'.

when doing a 'wp' the rest comand is as suspected not in the list... is there a way to activate the package if this has not been done in the installation process ?

Cheers
Adam

**Comment by danielbachhuber** [comment]
> when doing a 'wp' the rest comand is as suspected not in the list... is there a way to activate the package if this has not been done in the installation process ?

It should already be active.

Can you share the full output from `wp package install danielbachhuber/wp-rest-cli`? And also share `wp --info` ?

**Comment by a42** [comment]
Sure thing!

wp package install danielbachhuber/wp-rest-cli >>
Installing danielbachhuber/wp-rest-cli (dev-master)
Updating /home/vagrant/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
Success: Package installed successfully.

wp -info >> 
PHP binary:	/usr/bin/php5
PHP version:	5.5.32-1+deb.sury.org~trusty+1
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.23.0-alpha-a525ffd

... should WP-CLI global config and WP-CLI project config have a entity ? if so how to set them ?

Cheers,
Adam

**Comment by danielbachhuber** [comment]
> ... should WP-CLI global config and WP-CLI project config have a entity ? if so how to set them ?

No, WP-CLI will load the autoloader for the packages directory automatically.

Can you run `wp option get home --debug` and share output?

**Comment by a42** [comment]
yep!

On my local vagrant machine I got:

Debug: No readable global config found (0.116s)
Debug: No project config found (0.131s)
Debug: ABSPATH defined: /var/www/html/wordpress/ (0.38s)
Debug: Begin WordPress load (0.405s)
Debug: wp-config.php path: /var/www/html/wordpress/wp-config.php (0.423s)
Debug: Loaded WordPress (13.187s)
Debug: Running command: option get (13.261s)
http://wordpress.dev

:)

**Comment by danielbachhuber** [comment]
Crazy.

What version of WordPress are you running? And, to verify, you have the REST API plugin installed and activated?

**Comment by a42** [comment]
# #D*OH! 

I have now... And now it (of cource!) works...

Thanks for your help!

Cheers,
Ada,

**Comment by danielbachhuber** [comment]
@a42 Glad you got it figured out! I look forward to your feedback :) I've also added an explicit mention that the REST API needs to be installed and activated — sorry for the confusion.
