### ISSUE TITLE
Non-static method called statically.

### ISSUE THREAD

**Issue by dsifford** [danielbachhuber/wp-rest-cli#67]
Hi there,

Let me start by saying my PHP skills are terrible, so if this isn't an issue I apologize for bringing it up.

After installing this package, I received some errors in the console related to [this method](https://github.com/danielbachhuber/wp-rest-cli/blob/master/inc/Runner.php#L133) being called statically (on line 86 of the same file) when it's not written as a static method.

Thanks for your work on this. Looks pretty awesome. 👍

**Comment by danielbachhuber** [comment]
Thanks for the report! I'll get this fixed.
